version: "3.9"
services:
  api:
    image: webdevops/php-nginx-dev:7.4-alpine
    container_name: www
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/app
      - ./certs/rdas.vm.pem:/opt/docker/etc/nginx/ssl/server.crt
      - ./certs/rdas.vm-key.pem:/opt/docker/etc/nginx/ssl/server.key
  mysql:
    image: mysql:5.7
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "3lLNx6Ef3k1V"
      MYSQL_DATABASE: "www"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "88:80"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: "3306"
      PMA_USER: "user"
      PMA_PASSWORD: "password"
      PMA_DATABASE: "www"
      MAX_EXECUTION_TIME: 600
      UPLOAD_LIMIT: 200M
    depends_on:
      - mysql
